/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_nudt_hycloudclient_util_SignUtil */

#ifndef _Included_cn_edu_nudt_hycloudclient_util_SignUtil
#define _Included_cn_edu_nudt_hycloudclient_util_SignUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_nudt_hycloudclient_util_SignUtil
 * Method:    Sign
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_cn_edu_nudt_hycloudclient_util_SignUtil_Sign
  (JNIEnv *, jclass, jstring, jint, jstring, jstring);

/*
 * Class:     cn_edu_nudt_hycloudclient_util_SignUtil
 * Method:    generate_x_and_p
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_cn_edu_nudt_hycloudclient_util_SignUtil_generate_1x_1and_1p
  (JNIEnv *, jclass);

/*
 * Class:     cn_edu_nudt_hycloudclient_util_SignUtil
 * Method:    Verify
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_edu_nudt_hycloudclient_util_SignUtil_Verify
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     cn_edu_nudt_hycloudclient_util_SignUtil
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_edu_nudt_hycloudclient_util_SignUtil_greeting
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
