/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SignUtil */

#ifndef _Included_SignUtil
#define _Included_SignUtil
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     SignUtil
 * Method:    Sign
 * Signature: (Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_SignUtil_Sign
  (JNIEnv *, jclass, jstring, jint);
/*
 * Class:     SignUtil
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SignUtil_greeting
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
