/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_nudt_hycloudserver_util_DispatchHandler */

#ifndef _Included_cn_edu_nudt_hycloudserver_util_DispatchHandler
#define _Included_cn_edu_nudt_hycloudserver_util_DispatchHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_nudt_hycloudserver_util_DispatchHandler
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_edu_nudt_hycloudserver_util_DispatchHandler_greeting
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
